### ISSUE TITLE
After a Vorta crash, Output of `df` throws `df: /run/user/1000/doc: Operation not permitted`

### ISSUE THREAD

**Issue by felipehw** [flathub/com.borgbase.Vorta#23]
Hi.
After a Vorta crash, the output of `df` throws the error `df: /run/user/1000/doc: Operation not permitted`:

```
$ df -h
df: /run/user/1000/doc: Operation not permitted
Filesystem                            Size  Used Avail Use% Mounted on
devtmpfs                              7,8G     0  7,8G   0% /dev
tmpfs                                 7,8G   84K  7,8G   1% /dev/shm
tmpfs                                 7,8G  9,9M  7,8G   1% /run
/dev/mapper/fedora-root                68G   22G   43G  34% /sysroot
tmpfs                                 7,8G  108K  7,8G   1% /tmp
/dev/mapper/fedora-home                33G   16G   16G  50% /var/home
/dev/sda1                             976M  228M  682M  26% /boot
tmpfs                                 1,6G  212K  1,6G   1% /run/user/1000
```

This remains after remove Vorta and restart the machine.
Apparently, the machine got stuck on [document portal](https://flatpak.github.io/xdg-desktop-portal/portal-docs.html#gdbus-org.freedesktop.portal.Documents).

The log containing the error:
```

2020-06-06 00:11:20,905 - vorta.i18n - DEBUG - Loading translation failed for ['en', 'en-US', 'en-Latn-US'].
2020-06-06 00:11:20,939 - apscheduler.scheduler - INFO - Scheduler started
2020-06-06 00:11:21,385 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg --version
2020-06-06 00:11:53,208 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-06-06 00:11:53,208 - asyncio - DEBUG - Using selector: EpollSelector
2020-06-06 00:11:53,214 - root - DEBUG - Found 1 passwords matching repo URL.
2020-06-06 00:11:53,331 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg create --list --info --log-json --json --filter=AM -C lz4 --exclude-from /tmp/tmpq8sdyvbe /mnt/backup/felipe-backup/vorta/documents::dread-note-local-documents-2020-06-06T00:11:53 /mnt/home/home/dread/Documents
2020-06-06 00:11:54,794 - vorta.borg.borg_thread - INFO - Creating archive at "/mnt/backup/felipe-backup/vorta/documents::dread-note-local-documents-2020-06-06T00:11:53"
2020-06-06 00:14:28,454 - vorta.borg.borg_thread - DEBUG - Using VortaSecretStorageKeyring keyring to store passwords.
2020-06-06 00:14:28,455 - asyncio - DEBUG - Using selector: EpollSelector
2020-06-06 00:14:28,460 - root - DEBUG - Found 1 passwords matching repo URL.
2020-06-06 00:14:28,550 - vorta.borg.borg_thread - INFO - Running command /app/bin/borg check --info --log-json /mnt/backup/felipe-backup/vorta/documents::dread-note-local-documents-2020-06-06T00:11:53
2020-06-06 00:14:34,283 - vorta.borg.borg_thread - INFO - Starting repository check
2020-06-06 00:22:09,602 - vorta.borg.borg_thread - WARNING - Exception ignored in: <function Repository.__del__ at 0x7f56115d5680>
2020-06-06 00:22:09,605 - vorta.borg.borg_thread - WARNING - Traceback (most recent call last):
2020-06-06 00:22:09,605 - vorta.borg.borg_thread - WARNING - File "/app/lib/python3.7/site-packages/borg/repository.py", line 178, in __del__
2020-06-06 00:22:09,606 - vorta.borg.borg_thread - WARNING - self.close()
2020-06-06 00:22:09,607 - vorta.borg.borg_thread - WARNING - File "/app/lib/python3.7/site-packages/borg/repository.py", line 427, in close
2020-06-06 00:22:09,609 - vorta.borg.borg_thread - WARNING - self.lock.release()
2020-06-06 00:22:09,609 - vorta.borg.borg_thread - WARNING - File "/app/lib/python3.7/site-packages/borg/locking.py", line 383, in release
2020-06-06 00:22:09,609 - vorta.borg.borg_thread - WARNING - self._roster.modify(EXCLUSIVE, REMOVE)
2020-06-06 00:22:09,610 - vorta.borg.borg_thread - WARNING - File "/app/lib/python3.7/site-packages/borg/locking.py", line 282, in modify
2020-06-06 00:22:09,611 - vorta.borg.borg_thread - WARNING - elements.remove(self.id)
2020-06-06 00:22:09,612 - vorta.borg.borg_thread - WARNING - KeyError: (('dread-note-local@140737675714829', 22, 0),)
2020-06-06 00:22:09,613 - vorta.borg.borg_thread - ERROR - Local Exception
2020-06-06 00:22:09,615 - vorta.borg.borg_thread - ERROR - Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 327, in do_check
    if not repository.check(repair=args.repair, save_space=args.save_space):
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 923, in check
    objects = list(self.io.iter_objects(segment))
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 1378, in iter_objects
    read_data=read_data)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 1470, in _read
    data = fd.read(length)
OSError: [Errno 5] Input/output error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4501, in main
    exit_code = archiver.run(args)
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 4433, in run
    return set_ec(func(args))
  File "/app/lib/python3.7/site-packages/borg/archiver.py", line 166, in wrapper
    return method(self, args, repository=repository, **kwargs)
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 203, in __exit__
    self.close()
  File "/app/lib/python3.7/site-packages/borg/repository.py", line 427, in close
    self.lock.release()
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 383, in release
    self._roster.modify(EXCLUSIVE, REMOVE)
  File "/app/lib/python3.7/site-packages/borg/locking.py", line 282, in modify
    elements.remove(self.id)
KeyError: ('dread-note-local@140737675714829', 22, 0)

Platform: Linux dread-note-local 5.6.15-300.fc32.x86_64 #1 SMP Fri May 29 14:23:59 UTC 2020 x86_64
Linux:   
Borg: 1.1.10  Python: CPython 3.7.4 msgpack: 0.5.6
PID: 22  CWD: /var/home/dread
sys.argv: ['/app/bin/borg', 'check', '--info', '--log-json', '/mnt/backup/felipe-backup/vorta/documents::dread-note-local-documents-2020-06-06T00:11:53']
SSH_ORIGINAL_COMMAND: None
```

**Comment by TingPing** [comment]
As mentioned on IRC this permission is fine and how it behaves here. I don't think that is a problem in any way.

**Comment by felipehw** [comment]
> As mentioned on IRC this permission is fine and how it behaves here. I don't think that is a problem in any way.

I updated the description.

**Comment by Erick555** [comment]
`/run/user/1000/doc` is mounted as fuse filesystem and is used for flatpak portal. `df -h` seems not liked it but that has nothing to do with vorta app or its crash. You may reproduce it every time `/run/user/1000/doc` is mounted and mounting it is necessary for flatpak.

Similar (non)issues were reported before earlier https://github.com/flathub/im.riot.Riot/issues/108

In short: everything works as expected, nothing to see here.

**Comment by Hofer-Julian** [comment]
@TingPing & @Erick555 thanks for the explanation!

@felipehw if I understand you correctly you still found a reproduable crash. It would be great if you could explain this one in the vorta's main repository 😊

**Comment by felipehw** [comment]
@Hofer-Julian 
I always have problems with backuping to USB HDs (in different setups). With Vorta I just can extract a backup ... if I try something like check or mount ... it crash. But I won't report it cause I think this is from hardware (yet ... this happens with 2 different machines and 2 different USB HDs) ...

**Comment by felipehw** [comment]
@Erick555,
thanks!

Now I'm understanding better. These portals and these dynamic directories are all novelty to me.

But remains the case that in my tests in virtual machines if I restart the machine ... the `/run/user/1000/doc`  vanish and only reappears if I use any Flatpak.

In my physical machine, this directory always exists and there is a lot of empty folders and folders for apps that I removed a long time ago, e.g.: `/run/user/1000/doc/by-app/io.github.celluloid_player.Celluloid`. I can't remove these folders with `flatpak document-unexport` and they are listed in `flatpak documents`. Seems like zombie/phantom *documents*.

But this isn't a Vorta question and so ... I'll close the issue.
Thanks for everyone, very helpful people :D.

**Comment by Erick555** [comment]
@felipehw try removing `~/.local/share/flatpak/db` folder (you may copy it somewhere first in case you want to undo this) and restart.

**Comment by felipehw** [comment]
This worked!
Many thanks @Erick555 .

A question ... is there some documentation about what `~/.local/share/flatpak/db` is (explaining its content) or how *disruptive* can be the removal of this dir for configured apps?
